#trigger
language: objective-c
osx_image: beta-xcode6.3
sudo: true

cache:
  directories:
    - node_modules

install:
  - npm install -g mocha
  - npm install -g appium
  - appium -v
  - chmod +x ./as_current_user
  - appium-doctor --ios
  - sudo authorize_ios
  - chmod +x instruments-auth.sh
  # - ./instruments-auth.sh
  - pushd sample-code/examples/node/
  - npm install
  - appium --full-reset --log appium.log &
  - sleep 30
  - popd

script:
  - pushd sample-code/examples/node/
  - ../../../as_current_user "mocha ios-simple.js"
  - popd
  - cat appium.log
  
after_script:
  - cat appium.log

after_failure:
  - cat appium.log
