language: objective-c
osx_image: xcode6.4
sudo: true

install:
  - npm install -g appium
  - npm install -g mocha
  - pushd sample-code/examples/node/
  - npm install
  - popd
  - appium --full-reset &

script:
  - pushd sample-code/examples/node/
  - mocha ios-simple.js
  - popd
