language: objective-c
osx_image: xcode6.4
sudo: true

install:
  - npm install -g appium
  - npm install -g mocha
  - pushd sample-code/examples/node/
  - npm install
  - popd
  - sudo authorize_ios
  - appium --full-reset --log appium.log --show-sim-log &

script:
  - pushd sample-code/examples/node/
  - mocha ios-simple.js
  - popd
  - cat appium.log
  
after_script:
  - cat appium.log

after_failure:
  - cat appium.log
