language: objective-c
osx_image: xcode6.4
sudo: true

install:
  - npm install -g appium
  - npm install -g mocha
  - pushd sample-code/examples/node/
  - npm install
  - popd
  - appium --full-reset --log /var/tmp/appium.log &

script:
  - pushd sample-code/examples/node/
  - mocha ios-simple.js
  - popd
  - cat /var/tmp/appium.log
  
after_script:
  - cat /var/tmp/appium.log

after_failure:
  - cat /var/tmp/appium.log
