before_install:
  - npm install -g appium
  - npm install -g mocha
  
install:
  - pushd sample-code/examples/node/
  - npm install
  - popd

before_script:
  - appium &

script:
  - pushd sample-code/examples/node/
  - mocha ios-simple.js
  - popd

language: objective-c
osx_image: xcode6.4
sudo: true
